// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"github.com/google/uuid"
	"github.com/labstack/echo/v4"
)

// Event defines model for Event.
type Event struct {
	Id   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// EventNoId defines model for EventNoId.
type EventNoId struct {
	Name string `json:"name"`
}

// PostAddEventJSONRequestBody defines body for PostAddEvent for application/json ContentType.
type PostAddEventJSONRequestBody = EventNoId

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// TODO
	// (POST /addEvent)
	PostAddEvent(ctx echo.Context) error
	// TODO
	// (GET /allEvents)
	GetAllEvents(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostAddEvent converts echo context to params.
func (w *ServerInterfaceWrapper) PostAddEvent(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAddEvent(ctx)
	return err
}

// GetAllEvents converts echo context to params.
func (w *ServerInterfaceWrapper) GetAllEvents(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAllEvents(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/addEvent", wrapper.PostAddEvent)
	router.GET(baseURL+"/allEvents", wrapper.GetAllEvents)

}
