// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/google/uuid"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Event defines model for Event.
type Event struct {
	EndTime   time.Time `json:"end_time"`
	Id        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	StartTime time.Time `json:"start_time"`
}

// EventNoId defines model for EventNoId.
type EventNoId struct {
	EndTime   time.Time `json:"end_time"`
	Name      string    `json:"name"`
	StartTime time.Time `json:"start_time"`
}

// GetGetEventsParams defines parameters for GetGetEvents.
type GetGetEventsParams struct {
	// StartTime TODO
	StartTime time.Time `form:"start_time" json:"start_time"`

	// EndTime TODO
	EndTime time.Time `form:"end_time" json:"end_time"`
}

// PostAddEventJSONRequestBody defines body for PostAddEvent for application/json ContentType.
type PostAddEventJSONRequestBody = EventNoId

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// TODO
	// (POST /addEvent)
	PostAddEvent(ctx echo.Context) error
	// TODO - delete endpoint later
	// (GET /allEvents)
	GetAllEvents(ctx echo.Context) error
	// TODO
	// (GET /getEvents)
	GetGetEvents(ctx echo.Context, params GetGetEventsParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostAddEvent converts echo context to params.
func (w *ServerInterfaceWrapper) PostAddEvent(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAddEvent(ctx)
	return err
}

// GetAllEvents converts echo context to params.
func (w *ServerInterfaceWrapper) GetAllEvents(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAllEvents(ctx)
	return err
}

// GetGetEvents converts echo context to params.
func (w *ServerInterfaceWrapper) GetGetEvents(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGetEventsParams
	// ------------- Required query parameter "start_time" -------------

	err = runtime.BindQueryParameter("form", true, true, "start_time", ctx.QueryParams(), &params.StartTime)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter start_time: %s", err))
	}

	// ------------- Required query parameter "end_time" -------------

	err = runtime.BindQueryParameter("form", true, true, "end_time", ctx.QueryParams(), &params.EndTime)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter end_time: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetGetEvents(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/addEvent", wrapper.PostAddEvent)
	router.GET(baseURL+"/allEvents", wrapper.GetAllEvents)
	router.GET(baseURL+"/getEvents", wrapper.GetGetEvents)

}
