services:
  haproxy:
    image: haproxy:alpine
    container_name: haproxy
    ports:
      - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      cache_from:
        - type=registry,ref=eeritvan/calendar-frontend:buildcache
      args:
        VITE_BACKEND_URL: http://localhost:8081/api
    container_name: frontend
    depends_on:
      - backend

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      cache_from:
        - type=registry,ref=eeritvan/calendar-backend:buildcache
    container_name: backend
    environment:
      - DB_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
      - PORT=8081
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:alpine
    container_name: db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
