services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      cache_from:
        - type=registry,ref=eeritvan/calendar-frontend:buildcache
      args:
        VITE_BACKEND_URL: http://backend:8081/api
        VITE_WEBSOCKET_URL: ws://localhost:8081/api
    container_name: frontend
    ports:
      - "5173:3000"
    depends_on:
      - backend

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      cache_from:
        - type=registry,ref=eeritvan/calendar-backend:buildcache
    container_name: backend
    environment:
      - DB_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
      - PORT=8081
      - FRONTEND_ORIGIN=http://localhost:5173
    depends_on:
      - db
    ports:
      - "8081:8081"
    restart: on-failure

  db:
    image: postgres:alpine
    container_name: db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
