openapi: "3.0.0"
info:
  version: 1.0.0
  title:
paths:
  /allEvents:
    get:
      summary: TODO - delete endpoint later
      responses:
        "200":
          description: TODO
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Event"
  /addEvent:
    post:
      summary: TODO
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EventNoId"
      responses:
        "201":
          description: TODO
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Event"
  /getEvents:
    get:
      summary: TODO
      parameters:
        - in: query
          name: start_time
          schema:
            type: string
            format: date-time
            example: TODO
          required: true
          description: TODO
        - in: query
          name: end_time
          schema:
            type: string
            format: date-time
            example: TODO
          required: true
          description: TODO
      responses:
        "200":
          description: TODO
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Event"
components:
  schemas:
    Event:
      type: object
      required:
        - id
        - name
        - start_time
        - end_time
      properties:
        id:
          type: string
          format: uuid
          x-go-type: uuid.UUID
          x-go-type-import:
            path: github.com/google/uuid
          example: "019b7abf-0d2a-7240-bc33-68fc0a8a1118"
        name:
          type: string
          example: "event 1"
        start_time:
          type: string
          format: date-time
          example: 2022-01-02T16:00:00+07:00
        end_time:
          type: string
          format: date-time
          example: 2022-01-02T16:00:00+07:00
    EventNoId:
      type: object
      required:
        - name
        - start_time
        - end_time
      properties:
        name:
          type: string
          example: "event 1"
        start_time:
          type: string
          format: date-time
          example: 2022-01-02T16:00:00+07:00
        end_time:
          type: string
          format: date-time
          example: 2022-01-02T16:00:00+07:00
