openapi: "3.0.0"
info:
  version: 1.0.0
  title:
paths:
  /allEvents:
    get:
      summary: TODO
      responses:
        "200":
          description: TODO
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Event"
  /addEvent:
    post:
      summary: TODO
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EventNoId"
      responses:
        "201":
          description: TODO
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Event"
components:
  schemas:
    Event:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
          x-go-type: uuid.UUID
          x-go-type-import:
            path: github.com/google/uuid
          example: "019b7abf-0d2a-7240-bc33-68fc0a8a1118"
        name:
          type: string
          example: "event 1"
    EventNoId:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: "event 1"
