// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package sqlc

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const importCalendarEvents = `-- name: ImportCalendarEvents :batchexec
INSERT INTO Events (calendar_id, name, time)
SELECT $1, $2, tstzrange($4::timestamptz, $5::timestamptz, '[)')
FROM Calendars
WHERE id = $1 AND owner_id = $3
`

type ImportCalendarEventsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type ImportCalendarEventsParams struct {
	CalendarID uuid.UUID
	Name       string
	OwnerID    uuid.UUID
	StartTime  time.Time
	EndTime    time.Time
}

func (q *Queries) ImportCalendarEvents(ctx context.Context, arg []ImportCalendarEventsParams) *ImportCalendarEventsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.CalendarID,
			a.Name,
			a.OwnerID,
			a.StartTime,
			a.EndTime,
		}
		batch.Queue(importCalendarEvents, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &ImportCalendarEventsBatchResults{br, len(arg), false}
}

func (b *ImportCalendarEventsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *ImportCalendarEventsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
