// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendars.sql

package sqlc

import (
	"context"

	"github.com/eeritvan/calendar/internal/models"
	"github.com/google/uuid"
)

const addCalendar = `-- name: AddCalendar :one
INSERT INTO Calendars (name, owner_id)
VALUES ($1, $2)
RETURNING id, name, owner_id
`

type AddCalendarParams struct {
	Name    string
	OwnerID uuid.UUID
}

type AddCalendarRow struct {
	ID      uuid.UUID
	Name    string
	OwnerID uuid.UUID
}

func (q *Queries) AddCalendar(ctx context.Context, arg AddCalendarParams) (AddCalendarRow, error) {
	row := q.db.QueryRow(ctx, addCalendar, arg.Name, arg.OwnerID)
	var i AddCalendarRow
	err := row.Scan(&i.ID, &i.Name, &i.OwnerID)
	return i, err
}

const deleteCalendar = `-- name: DeleteCalendar :exec
DELETE FROM Calendars
WHERE id = $1 AND owner_id = $2
`

type DeleteCalendarParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) DeleteCalendar(ctx context.Context, arg DeleteCalendarParams) error {
	_, err := q.db.Exec(ctx, deleteCalendar, arg.ID, arg.OwnerID)
	return err
}

const editCalendar = `-- name: EditCalendar :one
UPDATE Calendars c
SET name = COALESCE($1, name)
WHERE c.id = $2 AND owner_id = $3
RETURNING id, name, owner_id
`

type EditCalendarParams struct {
	Name    string
	ID      uuid.UUID
	OwnerID uuid.UUID
}

type EditCalendarRow struct {
	ID      uuid.UUID
	Name    string
	OwnerID uuid.UUID
}

func (q *Queries) EditCalendar(ctx context.Context, arg EditCalendarParams) (EditCalendarRow, error) {
	row := q.db.QueryRow(ctx, editCalendar, arg.Name, arg.ID, arg.OwnerID)
	var i EditCalendarRow
	err := row.Scan(&i.ID, &i.Name, &i.OwnerID)
	return i, err
}

const editCalendarShared = `-- name: EditCalendarShared :exec
UPDATE Calendar_shares c
SET permission = $2
WHERE
    c.calendar_id = $3 AND
    c.shared_with = $4 AND
    c.calendar_id IN (SELECT c1.id FROM Calendars c1 WHERE c1.owner_id = $1)
`

type EditCalendarSharedParams struct {
	OwnerID    uuid.UUID
	Permission models.Permission
	CalendarID uuid.UUID
	SharedWith uuid.UUID
}

func (q *Queries) EditCalendarShared(ctx context.Context, arg EditCalendarSharedParams) error {
	_, err := q.db.Exec(ctx, editCalendarShared,
		arg.OwnerID,
		arg.Permission,
		arg.CalendarID,
		arg.SharedWith,
	)
	return err
}

const getCalendars = `-- name: GetCalendars :many
SELECT id, name, owner_id FROM Calendars
WHERE owner_id = $1
`

type GetCalendarsRow struct {
	ID      uuid.UUID
	Name    string
	OwnerID uuid.UUID
}

func (q *Queries) GetCalendars(ctx context.Context, ownerID uuid.UUID) ([]GetCalendarsRow, error) {
	rows, err := q.db.Query(ctx, getCalendars, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCalendarsRow
	for rows.Next() {
		var i GetCalendarsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.OwnerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserCalendarShare = `-- name: RemoveUserCalendarShare :exec
DELETE FROM Calendar_shares
WHERE calendar_id = $1 AND shared_with = $2
`

type RemoveUserCalendarShareParams struct {
	CalendarID uuid.UUID
	SharedWith uuid.UUID
}

func (q *Queries) RemoveUserCalendarShare(ctx context.Context, arg RemoveUserCalendarShareParams) error {
	_, err := q.db.Exec(ctx, removeUserCalendarShare, arg.CalendarID, arg.SharedWith)
	return err
}

const setCalendarPrivate = `-- name: SetCalendarPrivate :exec
UPDATE Calendars
SET visibility = 'private'
WHERE id = $1 AND owner_id = $2
`

type SetCalendarPrivateParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) SetCalendarPrivate(ctx context.Context, arg SetCalendarPrivateParams) error {
	_, err := q.db.Exec(ctx, setCalendarPrivate, arg.ID, arg.OwnerID)
	return err
}

const shareCalendar = `-- name: ShareCalendar :exec
INSERT INTO Calendar_shares (calendar_id, shared_with, permission)
VALUES ($1, $2, $3)
`

type ShareCalendarParams struct {
	CalendarID uuid.UUID
	SharedWith uuid.UUID
	Permission models.Permission
}

func (q *Queries) ShareCalendar(ctx context.Context, arg ShareCalendarParams) error {
	_, err := q.db.Exec(ctx, shareCalendar, arg.CalendarID, arg.SharedWith, arg.Permission)
	return err
}

const wipeShared = `-- name: WipeShared :exec
DELETE FROM Calendar_shares
WHERE
    calendar_id = $1 AND
    calendar_id IN (SELECT c1.id FROM Calendars c1 WHERE c1.owner_id = $2)
`

type WipeSharedParams struct {
	CalendarID uuid.UUID
	OwnerID    uuid.UUID
}

func (q *Queries) WipeShared(ctx context.Context, arg WipeSharedParams) error {
	_, err := q.db.Exec(ctx, wipeShared, arg.CalendarID, arg.OwnerID)
	return err
}
