// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendars.sql

package sqlc

import (
	"context"

	"github.com/eeritvan/calendar/internal/models"
	"github.com/google/uuid"
)

const addCalendar = `-- name: AddCalendar :one
INSERT INTO Calendars (name, owner_id)
VALUES ($1, $2)
RETURNING id, name, owner_id, visibility
`

type AddCalendarParams struct {
	Name    string
	OwnerID uuid.UUID
}

type AddCalendarRow struct {
	ID         uuid.UUID
	Name       string
	OwnerID    uuid.UUID
	Visibility models.Visibility
}

func (q *Queries) AddCalendar(ctx context.Context, arg AddCalendarParams) (AddCalendarRow, error) {
	row := q.db.QueryRow(ctx, addCalendar, arg.Name, arg.OwnerID)
	var i AddCalendarRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Visibility,
	)
	return i, err
}

const deleteAllCalendarShares = `-- name: DeleteAllCalendarShares :exec
DELETE FROM Calendar_shares cs
USING Calendars c
WHERE
    cs.calendar_id = $1
    AND c.id = cs.calendar_id
    AND c.owner_id = $2
`

type DeleteAllCalendarSharesParams struct {
	CalendarID uuid.UUID
	OwnerID    uuid.UUID
}

func (q *Queries) DeleteAllCalendarShares(ctx context.Context, arg DeleteAllCalendarSharesParams) error {
	_, err := q.db.Exec(ctx, deleteAllCalendarShares, arg.CalendarID, arg.OwnerID)
	return err
}

const deleteCalendar = `-- name: DeleteCalendar :exec
DELETE FROM Calendars
WHERE id = $1 AND owner_id = $2
`

type DeleteCalendarParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) DeleteCalendar(ctx context.Context, arg DeleteCalendarParams) error {
	_, err := q.db.Exec(ctx, deleteCalendar, arg.ID, arg.OwnerID)
	return err
}

const editCalendar = `-- name: EditCalendar :one
UPDATE Calendars c
SET name = COALESCE($1, name)
WHERE c.id = $2 AND owner_id = $3
RETURNING id, name, owner_id, visibility
`

type EditCalendarParams struct {
	Name    string
	ID      uuid.UUID
	OwnerID uuid.UUID
}

type EditCalendarRow struct {
	ID         uuid.UUID
	Name       string
	OwnerID    uuid.UUID
	Visibility models.Visibility
}

func (q *Queries) EditCalendar(ctx context.Context, arg EditCalendarParams) (EditCalendarRow, error) {
	row := q.db.QueryRow(ctx, editCalendar, arg.Name, arg.ID, arg.OwnerID)
	var i EditCalendarRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Visibility,
	)
	return i, err
}

const editSharedCalendarPermissions = `-- name: EditSharedCalendarPermissions :exec
UPDATE Calendar_shares cs
SET permission = $1
FROM Calendars c
WHERE
    cs.calendar_id = $2
    AND cs.shared_with = $3
    AND cs.calendar_id = c.id
    AND c.owner_id = $4
`

type EditSharedCalendarPermissionsParams struct {
	Permission models.Permission
	CalendarID uuid.UUID
	SharedWith uuid.UUID
	OwnerID    uuid.UUID
}

func (q *Queries) EditSharedCalendarPermissions(ctx context.Context, arg EditSharedCalendarPermissionsParams) error {
	_, err := q.db.Exec(ctx, editSharedCalendarPermissions,
		arg.Permission,
		arg.CalendarID,
		arg.SharedWith,
		arg.OwnerID,
	)
	return err
}

const getCalendars = `-- name: GetCalendars :many
SELECT
  c.id,
  c.name,
  c.owner_id,
  c.visibility
  -- cs.permission,
FROM Calendars c
LEFT JOIN Calendar_shares cs
  ON cs.calendar_id = c.id AND cs.shared_with = $1
WHERE
  c.owner_id = $1
  OR cs.shared_with = $1
`

type GetCalendarsRow struct {
	ID         uuid.UUID
	Name       string
	OwnerID    uuid.UUID
	Visibility models.Visibility
}

func (q *Queries) GetCalendars(ctx context.Context, sharedWith uuid.UUID) ([]GetCalendarsRow, error) {
	rows, err := q.db.Query(ctx, getCalendars, sharedWith)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCalendarsRow
	for rows.Next() {
		var i GetCalendarsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.Visibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCalendarShareMany = `-- name: RemoveCalendarShareMany :exec
DELETE FROM Calendar_shares cs
USING Calendars c
WHERE
    cs.calendar_id = $1
    AND cs.shared_with = ANY($3::uuid[])
    AND c.id = cs.calendar_id
    AND c.owner_id = $2
`

type RemoveCalendarShareManyParams struct {
	CalendarID    uuid.UUID
	OwnerID       uuid.UUID
	SharedWithIds []uuid.UUID
}

func (q *Queries) RemoveCalendarShareMany(ctx context.Context, arg RemoveCalendarShareManyParams) error {
	_, err := q.db.Exec(ctx, removeCalendarShareMany, arg.CalendarID, arg.OwnerID, arg.SharedWithIds)
	return err
}

const removeCalendarShareSelf = `-- name: RemoveCalendarShareSelf :exec
DELETE FROM Calendar_shares
WHERE calendar_id = $1 AND shared_with = $2
`

type RemoveCalendarShareSelfParams struct {
	CalendarID uuid.UUID
	SharedWith uuid.UUID
}

func (q *Queries) RemoveCalendarShareSelf(ctx context.Context, arg RemoveCalendarShareSelfParams) error {
	_, err := q.db.Exec(ctx, removeCalendarShareSelf, arg.CalendarID, arg.SharedWith)
	return err
}

const setCalendarPrivate = `-- name: SetCalendarPrivate :exec
UPDATE Calendars
SET visibility = 'private'
WHERE id = $1 AND owner_id = $2
`

type SetCalendarPrivateParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) SetCalendarPrivate(ctx context.Context, arg SetCalendarPrivateParams) error {
	_, err := q.db.Exec(ctx, setCalendarPrivate, arg.ID, arg.OwnerID)
	return err
}

const shareCalendar = `-- name: ShareCalendar :exec

INSERT INTO Calendar_shares (calendar_id, shared_with, permission)
SELECT $1, $2, $3
FROM Calendars
WHERE id = $1 AND owner_id = $4
`

type ShareCalendarParams struct {
	CalendarID uuid.UUID
	SharedWith uuid.UUID
	Permission models.Permission
	OwnerID    uuid.UUID
}

// ---- //// -----
func (q *Queries) ShareCalendar(ctx context.Context, arg ShareCalendarParams) error {
	_, err := q.db.Exec(ctx, shareCalendar,
		arg.CalendarID,
		arg.SharedWith,
		arg.Permission,
		arg.OwnerID,
	)
	return err
}
