// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addEvent = `-- name: AddEvent :one
INSERT INTO Events (calendar_id, name, time)
VALUES (
    $1,
    $2,
    tstzrange($3, $4, '[)')
)
RETURNING id, calendar_id, name, time
`

type AddEventParams struct {
	CalendarID  uuid.UUID
	Name        string
	Tstzrange   interface{}
	Tstzrange_2 interface{}
}

type AddEventRow struct {
	ID         uuid.UUID
	CalendarID uuid.UUID
	Name       string
	Time       pgtype.Range[pgtype.Timestamptz]
}

func (q *Queries) AddEvent(ctx context.Context, arg AddEventParams) (AddEventRow, error) {
	row := q.db.QueryRow(ctx, addEvent,
		arg.CalendarID,
		arg.Name,
		arg.Tstzrange,
		arg.Tstzrange_2,
	)
	var i AddEventRow
	err := row.Scan(
		&i.ID,
		&i.CalendarID,
		&i.Name,
		&i.Time,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM Events
WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const editEvent = `-- name: EditEvent :one
UPDATE Events
SET
    name = COALESCE($1, name),
    time = tstzrange(
        COALESCE($2, lower(time)),
        COALESCE($3, upper(time)),
        '[)'
    )
WHERE id = $4
RETURNING id, calendar_id, name, time
`

type EditEventParams struct {
	Name    string
	Column2 interface{}
	Column3 interface{}
	ID      uuid.UUID
}

type EditEventRow struct {
	ID         uuid.UUID
	CalendarID uuid.UUID
	Name       string
	Time       pgtype.Range[pgtype.Timestamptz]
}

func (q *Queries) EditEvent(ctx context.Context, arg EditEventParams) (EditEventRow, error) {
	row := q.db.QueryRow(ctx, editEvent,
		arg.Name,
		arg.Column2,
		arg.Column3,
		arg.ID,
	)
	var i EditEventRow
	err := row.Scan(
		&i.ID,
		&i.CalendarID,
		&i.Name,
		&i.Time,
	)
	return i, err
}

const getEvents = `-- name: GetEvents :many
SELECT id, calendar_id, name, time FROM Events
WHERE time && tstzrange($1, $2, '[)')
`

type GetEventsParams struct {
	Tstzrange   interface{}
	Tstzrange_2 interface{}
}

type GetEventsRow struct {
	ID         uuid.UUID
	CalendarID uuid.UUID
	Name       string
	Time       pgtype.Range[pgtype.Timestamptz]
}

func (q *Queries) GetEvents(ctx context.Context, arg GetEventsParams) ([]GetEventsRow, error) {
	rows, err := q.db.Query(ctx, getEvents, arg.Tstzrange, arg.Tstzrange_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsRow
	for rows.Next() {
		var i GetEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.CalendarID,
			&i.Name,
			&i.Time,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
