// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: folders.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addCalendarToFolder = `-- name: AddCalendarToFolder :exec
UPDATE Calendars
SET folder_id = $1
WHERE id = $2 AND owner_id = $3
`

type AddCalendarToFolderParams struct {
	FolderID uuid.UUID
	ID       uuid.UUID
	OwnerID  uuid.UUID
}

func (q *Queries) AddCalendarToFolder(ctx context.Context, arg AddCalendarToFolderParams) error {
	_, err := q.db.Exec(ctx, addCalendarToFolder, arg.FolderID, arg.ID, arg.OwnerID)
	return err
}

const addFolder = `-- name: AddFolder :one
INSERT INTO Folders (name, user_id)
VALUES ($1, $2)
RETURNING id, name
`

type AddFolderParams struct {
	Name   string
	UserID uuid.UUID
}

type AddFolderRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) AddFolder(ctx context.Context, arg AddFolderParams) (AddFolderRow, error) {
	row := q.db.QueryRow(ctx, addFolder, arg.Name, arg.UserID)
	var i AddFolderRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteFolder = `-- name: DeleteFolder :exec
DELETE FROM Folders
WHERE id = $1 AND user_id = $2
`

type DeleteFolderParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteFolder(ctx context.Context, arg DeleteFolderParams) error {
	_, err := q.db.Exec(ctx, deleteFolder, arg.ID, arg.UserID)
	return err
}

const editFolder = `-- name: EditFolder :exec
UPDATE Folders
SET name = $1
WHERE id = $2 AND user_id = $3
`

type EditFolderParams struct {
	Name   string
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) EditFolder(ctx context.Context, arg EditFolderParams) error {
	_, err := q.db.Exec(ctx, editFolder, arg.Name, arg.ID, arg.UserID)
	return err
}

const removeCalendarFromFolder = `-- name: RemoveCalendarFromFolder :exec
UPDATE Calendars
SET folder_id = NULL
WHERE id = $1 AND owner_id = $2
`

type RemoveCalendarFromFolderParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) RemoveCalendarFromFolder(ctx context.Context, arg RemoveCalendarFromFolderParams) error {
	_, err := q.db.Exec(ctx, removeCalendarFromFolder, arg.ID, arg.OwnerID)
	return err
}
