// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: folders.sql

package sqlc

import (
	"context"

	"github.com/eeritvan/calendar/internal/models"
	"github.com/google/uuid"
)

const addCalendarToFolder = `-- name: AddCalendarToFolder :one
WITH updated AS (
  UPDATE Calendars c
  SET folder_id = $1
  FROM Folders f
  WHERE c.id = $2
    AND c.owner_id = $3
    AND f.id = $1
    AND f.user_id = $3
  RETURNING c.id, c.name, c.owner_id, c.visibility, c.folder_id, (c.owner_id = $3) as is_owner
)
SELECT
  u.id,
  u.name,
  u.owner_id,
  u.visibility,
  u.folder_id,
  u.is_owner,
  f.name AS folder_name
FROM updated u
JOIN Folders f ON f.id = u.folder_id
`

type AddCalendarToFolderParams struct {
	FolderID uuid.UUID
	ID       uuid.UUID
	OwnerID  uuid.UUID
}

type AddCalendarToFolderRow struct {
	ID         uuid.UUID
	Name       string
	OwnerID    uuid.UUID
	Visibility models.Visibility
	FolderID   uuid.UUID
	IsOwner    bool
	FolderName string
}

func (q *Queries) AddCalendarToFolder(ctx context.Context, arg AddCalendarToFolderParams) (AddCalendarToFolderRow, error) {
	row := q.db.QueryRow(ctx, addCalendarToFolder, arg.FolderID, arg.ID, arg.OwnerID)
	var i AddCalendarToFolderRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Visibility,
		&i.FolderID,
		&i.IsOwner,
		&i.FolderName,
	)
	return i, err
}

const addFolder = `-- name: AddFolder :one
INSERT INTO Folders (name, user_id)
VALUES ($1, $2)
RETURNING id, name
`

type AddFolderParams struct {
	Name   string
	UserID uuid.UUID
}

type AddFolderRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) AddFolder(ctx context.Context, arg AddFolderParams) (AddFolderRow, error) {
	row := q.db.QueryRow(ctx, addFolder, arg.Name, arg.UserID)
	var i AddFolderRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteFolder = `-- name: DeleteFolder :exec
DELETE FROM Folders
WHERE id = $1 AND user_id = $2
`

type DeleteFolderParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteFolder(ctx context.Context, arg DeleteFolderParams) error {
	_, err := q.db.Exec(ctx, deleteFolder, arg.ID, arg.UserID)
	return err
}

const editFolder = `-- name: EditFolder :exec
UPDATE Folders
SET name = $1
WHERE id = $2 AND user_id = $3
`

type EditFolderParams struct {
	Name   string
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) EditFolder(ctx context.Context, arg EditFolderParams) error {
	_, err := q.db.Exec(ctx, editFolder, arg.Name, arg.ID, arg.UserID)
	return err
}

const removeCalendarFromFolder = `-- name: RemoveCalendarFromFolder :exec
UPDATE Calendars
SET folder_id = NULL
WHERE id = $1 AND owner_id = $2
`

type RemoveCalendarFromFolderParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) RemoveCalendarFromFolder(ctx context.Context, arg RemoveCalendarFromFolderParams) error {
	_, err := q.db.Exec(ctx, removeCalendarFromFolder, arg.ID, arg.OwnerID)
	return err
}
