// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addCalendar = `-- name: AddCalendar :one
INSERT INTO Calendars (name, owner_id)
VALUES ($1, $2)
RETURNING id, name, owner_id
`

type AddCalendarParams struct {
	Name    string
	OwnerID uuid.UUID
}

func (q *Queries) AddCalendar(ctx context.Context, arg AddCalendarParams) (Calendar, error) {
	row := q.db.QueryRow(ctx, addCalendar, arg.Name, arg.OwnerID)
	var i Calendar
	err := row.Scan(&i.ID, &i.Name, &i.OwnerID)
	return i, err
}

const addEvent = `-- name: AddEvent :one
INSERT INTO Events (calendar_id, name, time)
VALUES (
    $1,
    $2,
    tstzrange($3, $4, '[)')
)
RETURNING id, calendar_id, name, time
`

type AddEventParams struct {
	CalendarID  uuid.UUID
	Name        string
	Tstzrange   interface{}
	Tstzrange_2 interface{}
}

type AddEventRow struct {
	ID         uuid.UUID
	CalendarID uuid.UUID
	Name       string
	Time       pgtype.Range[pgtype.Timestamptz]
}

func (q *Queries) AddEvent(ctx context.Context, arg AddEventParams) (AddEventRow, error) {
	row := q.db.QueryRow(ctx, addEvent,
		arg.CalendarID,
		arg.Name,
		arg.Tstzrange,
		arg.Tstzrange_2,
	)
	var i AddEventRow
	err := row.Scan(
		&i.ID,
		&i.CalendarID,
		&i.Name,
		&i.Time,
	)
	return i, err
}

const deleteCalendar = `-- name: DeleteCalendar :exec
DELETE FROM Calendars
WHERE id = $1
`

func (q *Queries) DeleteCalendar(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCalendar, id)
	return err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM Events
WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const editCalendar = `-- name: EditCalendar :one
UPDATE Calendars
SET name = COALESCE($1, name)
WHERE id = $2
RETURNING id, name, owner_id
`

type EditCalendarParams struct {
	Name string
	ID   uuid.UUID
}

func (q *Queries) EditCalendar(ctx context.Context, arg EditCalendarParams) (Calendar, error) {
	row := q.db.QueryRow(ctx, editCalendar, arg.Name, arg.ID)
	var i Calendar
	err := row.Scan(&i.ID, &i.Name, &i.OwnerID)
	return i, err
}

const editEvent = `-- name: EditEvent :one
UPDATE Events
SET
    name = COALESCE($1, name),
    time = tstzrange(
        COALESCE($2, lower(time)),
        COALESCE($3, upper(time)),
        '[)'
    )
WHERE id = $4
RETURNING id, calendar_id, name, time
`

type EditEventParams struct {
	Name    string
	Column2 interface{}
	Column3 interface{}
	ID      uuid.UUID
}

type EditEventRow struct {
	ID         uuid.UUID
	CalendarID uuid.UUID
	Name       string
	Time       pgtype.Range[pgtype.Timestamptz]
}

func (q *Queries) EditEvent(ctx context.Context, arg EditEventParams) (EditEventRow, error) {
	row := q.db.QueryRow(ctx, editEvent,
		arg.Name,
		arg.Column2,
		arg.Column3,
		arg.ID,
	)
	var i EditEventRow
	err := row.Scan(
		&i.ID,
		&i.CalendarID,
		&i.Name,
		&i.Time,
	)
	return i, err
}

const getCalendars = `-- name: GetCalendars :many
SELECT id, name, owner_id FROM Calendars
WHERE owner_id = $1
`

func (q *Queries) GetCalendars(ctx context.Context, ownerID uuid.UUID) ([]Calendar, error) {
	rows, err := q.db.Query(ctx, getCalendars, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Calendar
	for rows.Next() {
		var i Calendar
		if err := rows.Scan(&i.ID, &i.Name, &i.OwnerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvents = `-- name: GetEvents :many
SELECT id, calendar_id, name, time FROM Events
WHERE time && tstzrange($1, $2, '[)')
`

type GetEventsParams struct {
	Tstzrange   interface{}
	Tstzrange_2 interface{}
}

type GetEventsRow struct {
	ID         uuid.UUID
	CalendarID uuid.UUID
	Name       string
	Time       pgtype.Range[pgtype.Timestamptz]
}

func (q *Queries) GetEvents(ctx context.Context, arg GetEventsParams) ([]GetEventsRow, error) {
	rows, err := q.db.Query(ctx, getEvents, arg.Tstzrange, arg.Tstzrange_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsRow
	for rows.Next() {
		var i GetEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.CalendarID,
			&i.Name,
			&i.Time,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const login = `-- name: Login :one
SELECT id, name, password_hash FROM Users
WHERE name = $1
`

func (q *Queries) Login(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, login, name)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.PasswordHash)
	return i, err
}

const signup = `-- name: Signup :one
INSERT INTO Users (name, password_hash)
VALUES ($1, $2)
RETURNING id, name
`

type SignupParams struct {
	Name         string
	PasswordHash string
}

type SignupRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) Signup(ctx context.Context, arg SignupParams) (SignupRow, error) {
	row := q.db.QueryRow(ctx, signup, arg.Name, arg.PasswordHash)
	var i SignupRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
