// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addEvent = `-- name: AddEvent :one
INSERT INTO Events (name)
VALUES ($1)
RETURNING id, name
`

type AddEventRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) AddEvent(ctx context.Context, name string) (AddEventRow, error) {
	row := q.db.QueryRow(ctx, addEvent, name)
	var i AddEventRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getEvents = `-- name: GetEvents :many
SELECT name, id FROM Events
`

func (q *Queries) GetEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(&i.Name, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
