// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const disableTotp = `-- name: DisableTotp :one
UPDATE Users
SET totp = NULL
WHERE id = $1
RETURNING id, name
`

type DisableTotpRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) DisableTotp(ctx context.Context, id uuid.UUID) (DisableTotpRow, error) {
	row := q.db.QueryRow(ctx, disableTotp, id)
	var i DisableTotpRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const enableTotp = `-- name: EnableTotp :one
UPDATE Users
SET totp = $1
WHERE id = $2
RETURNING id, name
`

type EnableTotpParams struct {
	Totp string
	ID   uuid.UUID
}

type EnableTotpRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) EnableTotp(ctx context.Context, arg EnableTotpParams) (EnableTotpRow, error) {
	row := q.db.QueryRow(ctx, enableTotp, arg.Totp, arg.ID)
	var i EnableTotpRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getTotpSecret = `-- name: GetTotpSecret :one
SELECT id, name, COALESCE(totp, '') AS totp
FROM Users
WHERE id = $1
`

type GetTotpSecretRow struct {
	ID   uuid.UUID
	Name string
	Totp string
}

func (q *Queries) GetTotpSecret(ctx context.Context, id uuid.UUID) (GetTotpSecretRow, error) {
	row := q.db.QueryRow(ctx, getTotpSecret, id)
	var i GetTotpSecretRow
	err := row.Scan(&i.ID, &i.Name, &i.Totp)
	return i, err
}

const login = `-- name: Login :one
SELECT id, name, password_hash, COALESCE(totp, '') AS totp
FROM Users
WHERE name = $1
`

func (q *Queries) Login(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, login, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PasswordHash,
		&i.Totp,
	)
	return i, err
}

const signup = `-- name: Signup :one
INSERT INTO Users (name, password_hash)
VALUES ($1, $2)
RETURNING id, name
`

type SignupParams struct {
	Name         string
	PasswordHash string
}

type SignupRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) Signup(ctx context.Context, arg SignupParams) (SignupRow, error) {
	row := q.db.QueryRow(ctx, signup, arg.Name, arg.PasswordHash)
	var i SignupRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
