// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const clearRecoveryCodes = `-- name: ClearRecoveryCodes :exec
DELETE FROM User_recovery_codes
WHERE user_id = $1
`

func (q *Queries) ClearRecoveryCodes(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearRecoveryCodes, userID)
	return err
}

const disableTotp = `-- name: DisableTotp :one
UPDATE Users
SET totp = NULL
WHERE id = $1
RETURNING id, name
`

type DisableTotpRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) DisableTotp(ctx context.Context, id uuid.UUID) (DisableTotpRow, error) {
	row := q.db.QueryRow(ctx, disableTotp, id)
	var i DisableTotpRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const enableTotp = `-- name: EnableTotp :one
UPDATE Users
SET totp = $1
WHERE id = $2
RETURNING id, name
`

type EnableTotpParams struct {
	Totp string
	ID   uuid.UUID
}

type EnableTotpRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) EnableTotp(ctx context.Context, arg EnableTotpParams) (EnableTotpRow, error) {
	row := q.db.QueryRow(ctx, enableTotp, arg.Totp, arg.ID)
	var i EnableTotpRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getTotpSecret = `-- name: GetTotpSecret :one
SELECT id, name, COALESCE(totp, '') AS totp
FROM Users
WHERE id = $1
`

type GetTotpSecretRow struct {
	ID   uuid.UUID
	Name string
	Totp string
}

func (q *Queries) GetTotpSecret(ctx context.Context, id uuid.UUID) (GetTotpSecretRow, error) {
	row := q.db.QueryRow(ctx, getTotpSecret, id)
	var i GetTotpSecretRow
	err := row.Scan(&i.ID, &i.Name, &i.Totp)
	return i, err
}

const getUnusedRecoveryCodes = `-- name: GetUnusedRecoveryCodes :many
SELECT id, code_hash
FROM User_recovery_codes
WHERE used_at IS NULL AND user_id = $1
`

type GetUnusedRecoveryCodesRow struct {
	ID       int32
	CodeHash string
}

func (q *Queries) GetUnusedRecoveryCodes(ctx context.Context, userID uuid.UUID) ([]GetUnusedRecoveryCodesRow, error) {
	rows, err := q.db.Query(ctx, getUnusedRecoveryCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnusedRecoveryCodesRow
	for rows.Next() {
		var i GetUnusedRecoveryCodesRow
		if err := rows.Scan(&i.ID, &i.CodeHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRecoveryCodes = `-- name: InsertRecoveryCodes :exec
INSERT INTO user_recovery_codes (user_id, code_hash)
SELECT $1, unnest($2::text[])
`

type InsertRecoveryCodesParams struct {
	UserID  uuid.UUID
	Column2 []string
}

func (q *Queries) InsertRecoveryCodes(ctx context.Context, arg InsertRecoveryCodesParams) error {
	_, err := q.db.Exec(ctx, insertRecoveryCodes, arg.UserID, arg.Column2)
	return err
}

const login = `-- name: Login :one
SELECT id, name, password_hash, COALESCE(totp, '') AS totp
FROM Users
WHERE name = $1
`

func (q *Queries) Login(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, login, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PasswordHash,
		&i.Totp,
	)
	return i, err
}

const setRecoveryCodeAsUsed = `-- name: SetRecoveryCodeAsUsed :exec
UPDATE user_recovery_codes
SET used_at = NOW()
WHERE id = $1
`

func (q *Queries) SetRecoveryCodeAsUsed(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, setRecoveryCodeAsUsed, id)
	return err
}

const signup = `-- name: Signup :one
INSERT INTO Users (name, password_hash)
VALUES ($1, $2)
RETURNING id, name
`

type SignupParams struct {
	Name         string
	PasswordHash string
}

type SignupRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) Signup(ctx context.Context, arg SignupParams) (SignupRow, error) {
	row := q.db.QueryRow(ctx, signup, arg.Name, arg.PasswordHash)
	var i SignupRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
