-- +goose Up
-- +goose StatementBegin
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE IF NOT EXISTS Users (
    id UUID PRIMARY KEY DEFAULT uuidv4(),
    name TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    totp TEXT
);

CREATE TABLE IF NOT EXISTS User_recovery_codes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES Users(id) ON DELETE CASCADE,
    code_hash TEXT NOT NULL,
    used_at TIMESTAMPTZ DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS Calendars (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    owner_id UUID NOT NULL REFERENCES Users(id) ON DELETE CASCADE,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Events (
    id   UUID DEFAULT uuidv7() PRIMARY KEY,
    calendar_id UUID NOT NULL REFERENCES Calendars(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    time TSTZRANGE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_events_time ON Events USING GIST (time);
CREATE INDEX IF NOT EXISTS idx_calendars_owner_id ON Calendars(owner_id);
CREATE INDEX IF NOT EXISTS idx_recovery_user ON user_recovery_codes(user_id);
-- +goose StatementEnd


-- +goose Down
-- +goose StatementBegin
DROP INDEX IF EXISTS idx_events_time;
DROP INDEX IF EXISTS idx_calendars_owner_id;
DROP INDEX IF EXISTS idx_recovery_user;

DROP TABLE IF EXISTS Events;
DROP TABLE IF EXISTS Calendars;
DROP TABLE IF EXISTS User_recovery_codes;
DROP TABLE IF EXISTS Users;
-- +goose StatementEnd
