BEGIN;

CREATE EXTENSION IF NOT EXISTS btree_gist;

ALTER TABLE IF EXISTS Events
ADD COLUMN IF NOT EXISTS time TSTZRANGE NOT NULL;

CREATE INDEX IF NOT EXISTS idx_events_time
ON Events USING GIST (time);

COMMIT;
