CREATE TABLE IF NOT EXISTS Calendars (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    name text NOT NULL
);

ALTER TABLE IF EXISTS Events
ADD COLUMN calendar_id UUID NOT NULL REFERENCES Calendars(id) ON DELETE CASCADE;
