// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/eeritvan/calendar/internal/sqlc"
	"github.com/google/uuid"
)

type Event struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Description *string         `json:"description,omitempty"`
	StartTime   time.Time       `json:"startTime"`
	EndTime     time.Time       `json:"endTime"`
	Color       sqlc.EventColor `json:"color"`
}

type EventChangePayload struct {
	Action string `json:"action"`
	Event  *Event `json:"event"`
}

type EventInput struct {
	Name        string          `json:"name"`
	Description *string         `json:"description,omitempty"`
	StartTime   time.Time       `json:"startTime"`
	EndTime     time.Time       `json:"endTime"`
	Color       sqlc.EventColor `json:"color"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}

type UpdateEventInput struct {
	Name        *string          `json:"name,omitempty"`
	Description *string          `json:"description,omitempty"`
	StartTime   *time.Time       `json:"startTime,omitempty"`
	EndTime     *time.Time       `json:"endTime,omitempty"`
	Color       *sqlc.EventColor `json:"color,omitempty"`
}
