/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarsGetCalendarsRouteImport } from './routes/calendars/getCalendars'
import { Route as CalendarsAddCalendarRouteImport } from './routes/calendars/addCalendar'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarsGetCalendarsRoute = CalendarsGetCalendarsRouteImport.update({
  id: '/calendars/getCalendars',
  path: '/calendars/getCalendars',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarsAddCalendarRoute = CalendarsAddCalendarRouteImport.update({
  id: '/calendars/addCalendar',
  path: '/calendars/addCalendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/calendars/addCalendar': typeof CalendarsAddCalendarRoute
  '/calendars/getCalendars': typeof CalendarsGetCalendarsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/calendars/addCalendar': typeof CalendarsAddCalendarRoute
  '/calendars/getCalendars': typeof CalendarsGetCalendarsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/calendars/addCalendar': typeof CalendarsAddCalendarRoute
  '/calendars/getCalendars': typeof CalendarsGetCalendarsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/calendars/addCalendar'
    | '/calendars/getCalendars'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/calendars/addCalendar'
    | '/calendars/getCalendars'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/calendars/addCalendar'
    | '/calendars/getCalendars'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  CalendarsAddCalendarRoute: typeof CalendarsAddCalendarRoute
  CalendarsGetCalendarsRoute: typeof CalendarsGetCalendarsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendars/getCalendars': {
      id: '/calendars/getCalendars'
      path: '/calendars/getCalendars'
      fullPath: '/calendars/getCalendars'
      preLoaderRoute: typeof CalendarsGetCalendarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendars/addCalendar': {
      id: '/calendars/addCalendar'
      path: '/calendars/addCalendar'
      fullPath: '/calendars/addCalendar'
      preLoaderRoute: typeof CalendarsAddCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  CalendarsAddCalendarRoute: CalendarsAddCalendarRoute,
  CalendarsGetCalendarsRoute: CalendarsGetCalendarsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
