package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"time"

	"github.com/eeritvan/calendar/graph/model"
	"github.com/eeritvan/calendar/internal/db"
	"github.com/eeritvan/calendar/internal/sqlc"
	"github.com/google/uuid"
)

// CreateEvent is the resolver for the createEvent field.
func (r *mutationResolver) CreateEvent(ctx context.Context, input model.EventInput) (*model.Event, error) {
	event, err := r.DB.Queries.CreateEvent(ctx, sqlc.CreateEventParams(input))
	if err != nil {
		return nil, err
	}

	return (*model.Event)(&event), nil
}

// UpdateEvent is the resolver for the updateEvent field.
func (r *mutationResolver) UpdateEvent(ctx context.Context, id uuid.UUID, input model.UpdateEventInput) (*model.Event, error) {
	event, err := r.DB.Queries.UpdateEvent(ctx, sqlc.UpdateEventParams{
		ID:          id,
		Name:        input.Name,
		Description: input.Description,
		StartTime:   input.StartTime,
		EndTime:     input.EndTime,
	})
	if err != nil {
		// todo: better error handling
		return nil, err
	}

	return (*model.Event)(&event), nil
}

// DeleteEvent is the resolver for the deleteEvent field.
func (r *mutationResolver) DeleteEvent(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.DB.Queries.DeleteEvent(ctx, id)
	if err != nil {
		// todo: better error handling
		return false, err
	}
	return true, nil
}

// AllEvents is the resolver for the allEvents field.
func (r *queryResolver) AllEvents(ctx context.Context) ([]*model.Event, error) {
	events, err := r.DB.Queries.ListEvents(ctx)
	if err != nil {
		// todo: better error handling
		return nil, err
	}

	modelEvents := make([]*model.Event, len(events))
	for i := range events {
		modelEvents[i] = (*model.Event)(&events[i])
	}

	return modelEvents, nil
}

// EventsByTimeRange is the resolver for the eventsByTimeRange field.
func (r *queryResolver) EventsByTimeRange(ctx context.Context, startTime time.Time, endTime time.Time) ([]*model.Event, error) {
	events, err := r.DB.Queries.EventsByTimeRange(ctx, sqlc.EventsByTimeRangeParams{
		StartTime: endTime,
		EndTime:   startTime,
	})

	if err != nil {
		// todo: better error handling
		return nil, err
	}

	modelEvents := make([]*model.Event, len(events))
	for i := range events {
		modelEvents[i] = (*model.Event)(&events[i])
	}

	return modelEvents, nil
}

// EventChanged is the resolver for the eventChanged field.
func (r *subscriptionResolver) EventChanged(ctx context.Context) (<-chan *model.EventChangePayload, error) {
	payloadChan := make(chan *model.EventChangePayload, 10)

	go func() {
		<-ctx.Done()
		close(payloadChan)
	}()

	err := r.DB.Listen(ctx, "events_channel", func(n db.EventNotification) {
		event := &model.Event{
			ID:          n.Data.ID,
			Name:        n.Data.Name,
			Description: n.Data.Description,
			StartTime:   n.Data.StartTime,
			EndTime:     n.Data.EndTime,
		}

		payload := &model.EventChangePayload{
			Action: n.Action,
			Event:  event,
		}

		select {
		case payloadChan <- payload:
		case <-ctx.Done():
			return
		}
	})

	if err != nil {
		close(payloadChan)
		return nil, err
	}

	return payloadChan, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
