name: frontend pipeline

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: frontend
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: Install dependencies
      run: bun install --frozen-lockfile
    - name: Check style
      run: bun run lint

  build:
    needs: [lint]
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: false
          tags: |
            ghcr.io/eeritvan/frontend:${{ github.sha }}
            ghcr.io/eeritvan/frontend:latest
          cache-from: type=registry,ref=ghcr.io/eeritvan/frontend:buildcache
          cache-to: type=registry,ref=ghcr.io/eeritvan/frontend:buildcache,mode=max
          outputs: type=docker,dest=${{ runner.temp }}/frontend-image.tar
      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-image
          path: ${{ runner.temp }}/frontend-image.tar