name: CI/CD pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  paths-filter:
    runs-on: ubuntu-24.04
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
      - name: Filter changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

  frontend:
    needs: [paths-filter]
    if: ${{ needs.paths-filter.outputs.frontend == 'true' }}
    uses: ./.github/workflows/frontend.yaml

  backend:
    needs: [paths-filter]
    if: ${{ needs.paths-filter.outputs.backend == 'true' }}
    uses: ./.github/workflows/backend.yaml

  e2e:
    needs: [paths-filter, frontend, backend]
    if: |
        always() && (
          (needs.paths-filter.outputs.frontend == 'true' ||
          needs.paths-filter.outputs.backend == 'true') &&
          (needs.frontend.result == 'success' || needs.frontend.result == 'skipped') &&
          (needs.backend.result == 'success' || needs.backend.result == 'skipped')
        )
    uses: ./.github/workflows/e2e.yaml

  deploy-frontend:
    needs: [paths-filter, e2e]
    if: |
      always() && (
        needs.paths-filter.outputs.frontend == 'true' &&
        needs.e2e.result == 'success'
      )
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: frontend
    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Download image artifact
      uses: actions/download-artifact@v4
      with:
        name: frontend-image
        path: ${{ runner.temp }}
    - name: Load image
      run: |
        docker load --input ${{ runner.temp }}/frontend-image.tar
    - name: Push Docker image
      run: |
        docker push ghcr.io/eeritvan/frontend:${{ github.sha }}
        docker push ghcr.io/eeritvan/frontend:latest

  deploy-backend:
    needs: [paths-filter, e2e]
    if: |
      always() && (
        needs.paths-filter.outputs.backend == 'true' &&
        needs.e2e.result == 'success'
      )
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Download image artifact
      uses: actions/download-artifact@v4
      with:
        name: backend-image
        path: ${{ runner.temp }}
    - name: Load image
      run: |
        docker load --input ${{ runner.temp }}/backend-image.tar
    - name: Push Docker image
      run: |
        docker push ghcr.io/eeritvan/backend:${{ github.sha }}
        docker push ghcr.io/eeritvan/backend:latest
